# Generated by Django 2.1.5 on 2021-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
