# Generated by Django 2.1.5 on 2021-03-08 10:37

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='null', upload_to=items.models.Item.get_img_upload_path),
        ),
    ]
