# Generated by Django 2.1.5 on 2021-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210308_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='item_Image',
            field=models.FileField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
