# Generated by Django 2.1.5 on 2021-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210309_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.FileField(default='images/default.png', upload_to='images/'),
        ),
    ]
