# Generated by Django 2.1.5 on 2021-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210309_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.ImageField(default='images/default/default.png', upload_to='images/'),
        ),
    ]
