# Generated by Django 2.1.5 on 2021-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210309_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='newItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('item_Image', models.ImageField(default='images/default/default.png', upload_to='images/')),
            ],
        ),
    ]
