# Generated by Django 2.1.5 on 2021-03-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_item_neuesfeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='neuesFeld',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
