# Generated by Django 3.1.7 on 2021-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20210325_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Neues Feld',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_Image',
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
