# Generated by Django 3.1.7 on 2021-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210325_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='Anzahl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='Farbe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='Titel',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='item_Image',
            field=models.ImageField(default='images/default/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.CharField(default='', max_length=120),
        ),
    ]
