# Generated by Django 3.1.7 on 2021-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20210325_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newItem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Farbe',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Titel',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Anzahl',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='additionalFields',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
