# Generated by Django 3.1.7 on 2021-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20210325_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='newItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('artist', models.CharField(default='', max_length=120)),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.CharField(default='', max_length=20)),
                ('item_Image', models.ImageField(default='images/default/default.png', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='additionalFields',
        ),
        migrations.RemoveField(
            model_name='item',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_Image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
