# Generated by Django 3.1.7 on 2021-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20210326_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='item_Image',
            field=models.FileField(default='images/default/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
