# Generated by Django 3.1.7 on 2021-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20210326_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='Kein Wert', max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Kein Wert', max_length=120),
        ),
    ]
