# Generated by Django 3.1.7 on 2021-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_delete_newitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_Image',
        ),
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
