# Generated by Django 3.1.7 on 2021-03-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_auto_20210326_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
