# Generated by Django 3.1.7 on 2021-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_auto_20210326_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='Kein Wert', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='item_Image',
            field=models.CharField(default='Kein Wert', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Kein Wert', max_length=120),
        ),
    ]
