# Generated by Django 3.1.7 on 2021-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_auto_20210326_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.CharField(default='', max_length=120),
        ),
    ]
