# Generated by Django 3.1.7 on 2021-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_item_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_Image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
