# Generated by Django 3.1.7 on 2021-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_auto_20210326_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test',
        ),
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(default='', max_length=100, verbose_name='Künstler'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('green', 'grün'), ('blue', 'blau'), ('white', 'weiß')], default='', max_length=120, verbose_name='Farbe'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=8000, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='item',
            name='glashuette',
            field=models.CharField(default='', max_length=100, verbose_name='Glashütte'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_Image',
            field=models.FileField(default='images/default/default.png', upload_to='images/', verbose_name='Bild des Objekts'),
        ),
        migrations.AddField(
            model_name='item',
            name='kindOf',
            field=models.CharField(choices=[('vase', 'Vase'), ('teelicht', 'Teelicht')], default='', max_length=100, verbose_name='art'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Objektname'),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
