# Generated by Django 3.1.7 on 2021-03-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_auto_20210326_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.DateField(verbose_name='Datum'),
        ),
    ]
