# Generated by Django 3.1.7 on 2021-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_auto_20210326_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(),
        ),
    ]
