# Generated by Django 3.1.7 on 2021-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0042_auto_20210326_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Künstler'),
        ),
    ]
