# Generated by Django 3.1.7 on 2021-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0047_auto_20210327_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.FileField(blank=True, default='images/default/default.png', upload_to='images/', verbose_name='Bild des Objekts'),
        ),
    ]
