# Generated by Django 3.1.7 on 2021-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0048_auto_20210327_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kindOf',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jahr'),
        ),
    ]
