# Generated by Django 3.1.7 on 2021-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0049_auto_20210329_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.ImageField(blank=True, default='images/default/default.png', upload_to='images/', verbose_name='Bild des Objekts'),
        ),
    ]
